---
title: "Explore bSims with Shiny apps"
author: "Peter Solymos"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simulation workflow in bSims}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
par(mar = c(1, 1, 1, 1))
set.seed(429)
suppressPackageStartupMessages(library(bSims))
```

bSims comes with a few [Shiny](https://shiny.posit.co/) apps.
These can be used to interactively explore the effects of different settings.

Compare distance functions:

```{r eval=FALSE}
run_app("distfunH")
run_app("distfunHER")
```

Compare simulation settings for a single landscape:

```{r eval=FALSE}
run_app("bsimsH")
run_app("bsimsHER")
```

The [Shinylive](https://shinylive.io/r/examples/) versions of the apps can be found here:

- [`distfunH`](https://peter.solymos.org/bSims/apps/distfunH/)
- [`distfunHER`](https://peter.solymos.org/bSims/apps/distfunHER/)
- [`bsimsH`](https://peter.solymos.org/bSims/apps/bsimsH/)
- [`bsimsHER`](https://peter.solymos.org/bSims/apps/bsimsHER/)
