---
title: "Limitations and extensions"
author: "Peter Solymos"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Limitations and extensions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
par(mar = c(1, 1, 1, 1))
set.seed(429)
```

The package is not equipped with all the possible ways to estimate the
model parameters. It only has rudimentary removal modeling and 
distance sampling functionality implemented for the interactive
visualization and testing purposes.
Estimating parameters for more complex situations (i.e.
finite mixture removal models, or via Hazard rate distance functions)
or estimating abundance via multiple-visit N-mixture models etc. is
outside of the scope of the package and it is the responsibility of the 
user to make sure those work as expected. Although there is an
ever increasing set of scripts coversing some of these aspects
in the [`/inst/tmp`](https://github.com/psolymos/bSims/tree/master/inst/tmp) 
folder of the package and in the 
[_QPAD book_](https://peter.solymos.org/qpad-book/).

Other intentional limitation of the package is the lack of
reverse interactions between the layers. For example
the presence of an observer could influence behavior
of the birds close to the observer. Such features can
be implemented as methods extending the current functionality.

Another limitation is that this implementation considers single
species. Observers rarely collect data on single species 
but rather count multiple species as part of the same survey.
The commonness of the species, observer ability, etc. can influence
the observation process when the whole community is considered.
Such scenarios are also not considered at present. Although the same
landscape can be reused for multiple species, and building up
the simulation that way.

The package considers simulations as independent 
in space and time. When larger landscapes need to be simulated, 
there might be several options: 
(1) simulate a larger extent and put multiple independent observers 
into the landscape; or (2) simulate independent landscapes in isolation.
The latter approach can also address spatial and temporal
heterogeneity in density, behaviour, etc. E.g. if
singing rate is changing as a function of time of day,
one can define the `vocal_rate` values as a function of time,
and simulate independent animation layers.
When the density varies in space, one can
simulate independent population layers.

These limitations can be addressed as additional methods and
modules extending the capabilities of the package, 
or as added functionality to the core layer functions
in future releases.

